// Generated by https://quicktype.io

export interface PaytientResponse {
  address: Address;
  allowance: null;
  balance: number;
  cvv: null;
  description: string;
  expiration: string;
  externalSystem: string;
  id: number;
  lastFour: string;
  network: string;
  pan: null;
  program: string;
  shippingEta: null;
  shippingStatus: null;
  status: string;
  type: string;
  zipCode: string;
}

export interface Address {
  addressLine1: string;
  addressLine2: null;
  city: string;
  state: string;
  zipCode: string;
}
